[build]
  base = "frontend"
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://yemek5-backend.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 