services:
  - type: web
    name: yemek5-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npx prisma generate
    startCommand: cd backend && npx prisma db push && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://yemek5_user:password@host:port/yemek5_db
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-change-this-in-production
      - key: FRONTEND_URL
        value: https://siparisnet.netlify.app 