services:
  - type: web
    name: yemek5-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SERVER_PORT
        value: 3001
      - key: FRONTEND_URL
        value: https://yemek5-frontend.onrender.com 