services:
  - type: web
    name: yemek5-backend
    env: node
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: file:./dev.db
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://siparisnet.netlify.app 