services:
  - type: web
    name: yemek5-backend
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: npm run run-migration && npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://naim:cibKjxXirpnFyQTor7DpBhGXf1XAqmmw@dpg-d1podn2dbo4c73bp2q7g-a.oregon-postgres.render.com/siparis
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-change-this-in-production
      - key: FRONTEND_URL
        value: https://siparisnet.netlify.app 